name: Build Artifacts
on:
  workflow_call:

jobs:
  stevejobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checking artifacts
        run: echo ${{ github.ref }}
      - name: GITHUB_REPOSITORY
        run: echo $GITHUB_REPOSITORY
      - name: GITHUB_SHA
        run: echo $GITHUB_SHA
      - name: GITHUB_ACTOR 1
        run: echo $GITHUB_ACTOR
      - name: GITHUB_ACTOR 2
        run: echo ${{ github.actor }}
      - name: TOKEN
        run: echo ${{ secrets.GITHUB_TOKEN }}
      - name: Secret
        run: echo ${{ secrets.IM_A_SECRET }}
