name: Build Artifacts
on:
  workflow_call:

jobs:
  stevejobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checking artifacts
        run: echo ${{ github.ref }}
      - name: Fail me
        run: exit 1
