name: Build Cherry-Pick
on:
  push:
    branches: [ release ]
jobs:
  check-cherry-pick:
    runs-on: ubuntu-latest
    outputs:
      isCherryPick: ${{ steps.set-isCherryPick.outputs.isCherryPick }}
    steps:
      - name: Check if workflow should perform build
        id: set-isCherryPick
        run: >
          curl -L -s -w \"%{http_code}\" -o /dev/null -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
          https://docker.pkg.github.com/v2/${GITHUB_REPOSITORY}/manifests/git-${GITHUB_SHA::7}
          | grep -q 200
          && echo "::set-output name=isCherryPick::false"
          || echo "::set-output name=isCherryPick::true"

  doSomethingOnCherryPick:
    needs: [check-cherry-pick]
    if: needs.check-cherry-pick.outputs.isCherryPick == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: echo "Im doing something cause im a cherry pick"
