name: Chained Workflow
on:
  workflow_run:
    workflows: ["Simple Workflow", "Failing Workflow"]
    types:
      - completed
jobs:
  doSomething:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
