name: Conclusion Test on Simple Worfklow
on:
  workflow_run:
    workflows: ["Simple Workflow"]
    types:
      - completed
jobs:
  checkConclusion:
    env: 
    RELEASE_SHA: ${{ github.event.workflow_run.head_sha }}
    DEPLOYABLE: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Current SHA
        run: echo $GITHUB_SHA
      - name: Get Release Container Tag
        run: echo git-${RELEASE_SHA}::7 
      - run: if $DEPLOYABLE ; then echo 'Yes, its deployable' ; else echo 'No its not deployable' && exit 1 ; fi
        name: Checking
  doSomething:
    if: ${DEPLOYABLE}
    needs: [checkConclusion]
    runs-on: ubuntu-latest
    steps:
      - run: echo "im doing something"
        name: Something
  doAlways:
    needs: [doSomething]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: echo "im doing something on failure"
        name: On Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
