name: Deploy Production
on:
  push:
    branches: [release]

jobs:
  build-artifact:
    uses: philib/github-actions-test/.github/workflows/build-artifacts.yml@release
  check-artifact:
    needs: [ build-artifact ]
    if: always()
    env:
      DEPLOYABLE: ${{ needs.build-artifact.result == 'success' || needs.build-artifact.result == 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Result
        run: echo ${{ needs.build-aritfact.result }}
      - name: Checking artifact
        run: if $DEPLOYABLE ; then echo "Start deployment of GitHub SHA ${GITHUB_SHA}..." ; else echo 'Can not deploy due to missing artifacts' && exit 1 ; fi
  deploy:
    needs: [ check-artifact ]
    runs-on: ubuntu-latest
    steps:
      - name: Starting Deployment
        run: echo "Starting Deployment of ${{ github.ref }}"

