name: Deploy Production
on:
  workflow_run:
    workflows: ["Build Cherry-Pick"]
    branches: [release]
    types: [completed]
env: 
  RELEASE_SHA: ${{ github.event.workflow_run.head_sha }}
jobs:
  check-deployment:
    env: 
      DEPLOYABLE: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'skipped' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking artifacts
        run: if $DEPLOYABLE ; then echo 'Start deployment...' ; else echo 'Can not deploy due to missing artifacts' && exit 1 ; fi
        
  # validate ------------------------------------------------

  validate-deployment:
    needs: check-deployment
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the GITHUB_SHA ${GITHUB_SHA::7}"
      - run: echo "Deploy Container with tag git-${RELEASE_SHA::7}"
