name: Deploy Production
on:
  push:
    branches: [release]

jobs:
  call-workflow:
    uses: philib/github-actions-test/.github/workflows/build-artifacts.yml@release
  print-job:
    needs: [ call-workflow ]
    runs-on: ubuntu-latest
    steps:
      - name: Print this
        run: echo ${{ github.ref }}

