name: Skipped Workflow Test
on:
  push:
    branches: [main]
jobs:
  doNothing:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This should not be printed"
  check-failure:
    needs:
      - doNothing
    if: ${{ always() && !contains(needs.*.result,'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "Please print this"
      - name: result
        run: echo ${{ needs.doNothing.result }}
      - name: result2
        run: echo ${{ needs.doNothing.result }}
  doSomething:
    needs: [check-failure]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: echo "Please print this"
      - run: echo ${{ needs.check-failure.result }}
